// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYm8JeY4fsENZSqD3jcB6p2fpIeyNXFw',
    appId: '1:556986113836:web:3331e43171f27081b0d689',
    messagingSenderId: '556986113836',
    projectId: 'universidadtest-cccae',
    authDomain: 'universidadtest-cccae.firebaseapp.com',
    storageBucket: 'universidadtest-cccae.firebasestorage.app',
    measurementId: 'G-17680NJP07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzO-2yA4VI_S6-EqSdjWXzuKX0DxT03ss',
    appId: '1:556986113836:android:cbec45036b77cd3eb0d689',
    messagingSenderId: '556986113836',
    projectId: 'universidadtest-cccae',
    storageBucket: 'universidadtest-cccae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg0aveKmOwRPAh9Zbu-qvge5DMumjajRE',
    appId: '1:556986113836:ios:73200a74468e2df6b0d689',
    messagingSenderId: '556986113836',
    projectId: 'universidadtest-cccae',
    storageBucket: 'universidadtest-cccae.firebasestorage.app',
    iosBundleId: 'com.example.tallermovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg0aveKmOwRPAh9Zbu-qvge5DMumjajRE',
    appId: '1:556986113836:ios:73200a74468e2df6b0d689',
    messagingSenderId: '556986113836',
    projectId: 'universidadtest-cccae',
    storageBucket: 'universidadtest-cccae.firebasestorage.app',
    iosBundleId: 'com.example.tallermovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbYm8JeY4fsENZSqD3jcB6p2fpIeyNXFw',
    appId: '1:556986113836:web:61c3fc843ec3f242b0d689',
    messagingSenderId: '556986113836',
    projectId: 'universidadtest-cccae',
    authDomain: 'universidadtest-cccae.firebaseapp.com',
    storageBucket: 'universidadtest-cccae.firebasestorage.app',
    measurementId: 'G-5BKC4MJDVX',
  );
}
