"""add_fcm_token_to_users

Revision ID: 406d0bdf8bf2
Revises: db886be18330
Create Date: 2026-04-24 17:24:19.309317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406d0bdf8bf2'
down_revision: Union[str, None] = 'db886be18330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    op.add_column('usuario', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fcm_token')
    op.drop_column('cliente', 'fcm_token')
    # ### end Alembic commands ###
