"""Add audio_url to chat

Revision ID: 5f2851fd03f7
Revises: 88c2a9b6e49c
Create Date: 2026-04-26 15:21:01.657230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2851fd03f7'
down_revision: Union[str, None] = '88c2a9b6e49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emergencia_idPago_fkey'), 'emergencia', type_='foreignkey')
    op.drop_column('emergencia', 'idPago')
    op.add_column('mensajes_chat', sa.Column('audio_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes_chat', 'audio_url')
    op.add_column('emergencia', sa.Column('idPago', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('emergencia_idPago_fkey'), 'emergencia', 'pago', ['idPago'], ['id'])
    # ### end Alembic commands ###
