"""add_fcm_token_table

Revision ID: 71c88c7c209a
Revises: 7995839912cd
Create Date: 2026-04-24 17:10:44.422040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c88c7c209a'
down_revision: Union[str, None] = '7995839912cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('dispositivo', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_fcm_token_id'), 'fcm_token', ['id'], unique=False)
    op.create_index(op.f('ix_fcm_token_idUsuario'), 'fcm_token', ['idUsuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fcm_token_idUsuario'), table_name='fcm_token')
    op.drop_index(op.f('ix_fcm_token_id'), table_name='fcm_token')
    op.drop_table('fcm_token')
    # ### end Alembic commands ###
