"""auto_sync_1777153855

Revision ID: 788eff625d24
Revises: da589baea6e0
Create Date: 2026-04-25 17:50:56.180541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788eff625d24'
down_revision: Union[str, None] = 'da589baea6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('ultimo4', sa.String(length=4), nullable=True),
    sa.Column('es_predeterminado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id')
    )
    op.create_index(op.f('ix_metodo_pago_id'), 'metodo_pago', ['id'], unique=False)
    op.add_column('cliente', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('pago', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.add_column('pago', sa.Column('emergencia_id', sa.Integer(), nullable=False))
    op.add_column('pago', sa.Column('stripe_intent_id', sa.String(length=255), nullable=True))
    op.add_column('pago', sa.Column('metodo_pago_id', sa.String(length=255), nullable=True))
    op.add_column('pago', sa.Column('estado', sa.String(length=50), server_default='PENDIENTE', nullable=False))
    op.create_foreign_key(None, 'pago', 'emergencia', ['emergencia_id'], ['id'])
    op.create_foreign_key(None, 'pago', 'cliente', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pago', type_='foreignkey')
    op.drop_constraint(None, 'pago', type_='foreignkey')
    op.drop_column('pago', 'estado')
    op.drop_column('pago', 'metodo_pago_id')
    op.drop_column('pago', 'stripe_intent_id')
    op.drop_column('pago', 'emergencia_id')
    op.drop_column('pago', 'cliente_id')
    op.drop_column('cliente', 'stripe_customer_id')
    op.drop_index(op.f('ix_metodo_pago_id'), table_name='metodo_pago')
    op.drop_table('metodo_pago')
    # ### end Alembic commands ###
