"""lll

Revision ID: 7995839912cd
Revises: d5512058481b
Create Date: 2026-04-18 19:41:53.200305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7995839912cd'
down_revision: Union[str, None] = 'd5512058481b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_correo'), 'cliente', ['correo'], unique=True)
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_especialidad_id'), 'especialidad', ['id'], unique=False)
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_nombre'), 'estado', ['nombre'], unique=True)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('MontoComision', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fechaPago', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_id'), 'pago', ['id'], unique=False)
    op.create_table('prioridad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taller',
    sa.Column('cod', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['usuario.id'], name='fk_taller_admin', use_alter=True),
    sa.PrimaryKeyConstraint('cod')
    )
    op.create_index(op.f('ix_taller_cod'), 'taller', ['cod'], unique=False)
    op.create_table('asignacion_especialidad',
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.Column('idEspecialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEspecialidad'], ['especialidad.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['taller.cod'], ),
    sa.PrimaryKeyConstraint('idTaller', 'idEspecialidad')
    )
    op.create_table('categoria_problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('idEspecialidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEspecialidad'], ['especialidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['idTaller'], ['taller.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnico_correo'), 'tecnico', ['correo'], unique=True)
    op.create_index(op.f('ix_tecnico_id'), 'tecnico', ['id'], unique=False)
    op.create_index(op.f('ix_tecnico_idTaller'), 'tecnico', ['idTaller'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['idTaller'], ['taller.cod'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_idTaller'), 'usuario', ['idTaller'], unique=False)
    op.create_table('vehiculo',
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('placa')
    )
    op.create_index(op.f('ix_vehiculo_idCliente'), 'vehiculo', ['idCliente'], unique=False)
    op.create_index(op.f('ix_vehiculo_placa'), 'vehiculo', ['placa'], unique=False)
    op.create_table('emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('textoAdicional', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fecha', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('idTaller', sa.String(length=10), nullable=True),
    sa.Column('idPrioridad', sa.Integer(), nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('placaVehiculo', sa.String(length=20), nullable=False),
    sa.Column('idPago', sa.Integer(), nullable=True),
    sa.Column('idEstado', sa.Integer(), server_default='1', nullable=False),
    sa.Column('locked_by', sa.String(length=10), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categoria_problema.id'], ),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['idEstado'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['idPago'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['idPrioridad'], ['prioridad.id'], ),
    sa.ForeignKeyConstraint(['idTaller'], ['taller.cod'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['taller.cod'], ),
    sa.ForeignKeyConstraint(['placaVehiculo'], ['vehiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergencia_id'), 'emergencia', ['id'], unique=False)
    op.create_index(op.f('ix_emergencia_idCliente'), 'emergencia', ['idCliente'], unique=False)
    op.create_index(op.f('ix_emergencia_idEstado'), 'emergencia', ['idEstado'], unique=False)
    op.create_index(op.f('ix_emergencia_idTaller'), 'emergencia', ['idTaller'], unique=False)
    op.create_index(op.f('ix_emergencia_placaVehiculo'), 'emergencia', ['placaVehiculo'], unique=False)
    op.create_table('tecnico_especialidad',
    sa.Column('idTecnico', sa.Integer(), nullable=False),
    sa.Column('idEspecialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEspecialidad'], ['especialidad.id'], ),
    sa.ForeignKeyConstraint(['idTecnico'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('idTecnico', 'idEspecialidad')
    )
    op.create_table('asignacion_tecnico_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idTecnico', sa.Integer(), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['emergencia.id'], ),
    sa.ForeignKeyConstraint(['idTecnico'], ['tecnico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignacion_tecnico_emergencia_idEmergencia'), 'asignacion_tecnico_emergencia', ['idEmergencia'], unique=False)
    op.create_index(op.f('ix_asignacion_tecnico_emergencia_idTecnico'), 'asignacion_tecnico_emergencia', ['idTecnico'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['emergencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_idEmergencia'), 'evidencia', ['idEmergencia'], unique=False)
    op.create_table('historial_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechaCambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.Column('idEstado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['emergencia.id'], ),
    sa.ForeignKeyConstraint(['idEstado'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estado_idEmergencia'), 'historial_estado', ['idEmergencia'], unique=False)
    op.create_table('resumen_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Resumen', sa.Text(), nullable=False),
    sa.Column('FichaTecnica', sa.JSON(), nullable=True),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmergencia'], ['emergencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumen_ia_idEmergencia'), 'resumen_ia', ['idEmergencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumen_ia_idEmergencia'), table_name='resumen_ia')
    op.drop_table('resumen_ia')
    op.drop_index(op.f('ix_historial_estado_idEmergencia'), table_name='historial_estado')
    op.drop_table('historial_estado')
    op.drop_index(op.f('ix_evidencia_idEmergencia'), table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_asignacion_tecnico_emergencia_idTecnico'), table_name='asignacion_tecnico_emergencia')
    op.drop_index(op.f('ix_asignacion_tecnico_emergencia_idEmergencia'), table_name='asignacion_tecnico_emergencia')
    op.drop_table('asignacion_tecnico_emergencia')
    op.drop_table('tecnico_especialidad')
    op.drop_index(op.f('ix_emergencia_placaVehiculo'), table_name='emergencia')
    op.drop_index(op.f('ix_emergencia_idTaller'), table_name='emergencia')
    op.drop_index(op.f('ix_emergencia_idEstado'), table_name='emergencia')
    op.drop_index(op.f('ix_emergencia_idCliente'), table_name='emergencia')
    op.drop_index(op.f('ix_emergencia_id'), table_name='emergencia')
    op.drop_table('emergencia')
    op.drop_index(op.f('ix_vehiculo_placa'), table_name='vehiculo')
    op.drop_index(op.f('ix_vehiculo_idCliente'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_usuario_idTaller'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tecnico_idTaller'), table_name='tecnico')
    op.drop_index(op.f('ix_tecnico_id'), table_name='tecnico')
    op.drop_index(op.f('ix_tecnico_correo'), table_name='tecnico')
    op.drop_table('tecnico')
    op.drop_table('categoria_problema')
    op.drop_table('asignacion_especialidad')
    op.drop_index(op.f('ix_taller_cod'), table_name='taller')
    op.drop_table('taller')
    op.drop_table('prioridad')
    op.drop_index(op.f('ix_pago_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_estado_nombre'), table_name='estado')
    op.drop_table('estado')
    op.drop_index(op.f('ix_especialidad_id'), table_name='especialidad')
    op.drop_table('especialidad')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_correo'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
