"""Add detalle_factura to Pago

Revision ID: 884894744566
Revises: a5263e9cd5af
Create Date: 2026-04-26 15:59:56.635808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884894744566'
down_revision: Union[str, None] = 'a5263e9cd5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('detalle_factura', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pago', 'detalle_factura')
    # ### end Alembic commands ###
