"""auto_sync_1777226470

Revision ID: 88c2a9b6e49c
Revises: d47f912bf928
Create Date: 2026-04-26 14:01:11.036036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c2a9b6e49c'
down_revision: Union[str, None] = 'd47f912bf928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
