"""auto_sync_1777231604

Revision ID: a5263e9cd5af
Revises: 5f2851fd03f7
Create Date: 2026-04-26 15:26:45.901163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5263e9cd5af'
down_revision: Union[str, None] = '5f2851fd03f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
