"""auto_sync_1777217770

Revision ID: d47f912bf928
Revises: eb96b71c5822
Create Date: 2026-04-26 11:36:12.968118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47f912bf928'
down_revision: Union[str, None] = 'eb96b71c5822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEmergencia', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('rol_remitente', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEmergencia'], ['emergencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_chat_id'), 'mensajes_chat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_chat_id'), table_name='mensajes_chat')
    op.drop_table('mensajes_chat')
    # ### end Alembic commands ###
