"""add_ai_validation_fields

Revision ID: da589baea6e0
Revises: b989cf2e01ab
Create Date: 2026-04-24 18:50:16.259895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da589baea6e0'
down_revision: Union[str, None] = 'b989cf2e01ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencia', sa.Column('es_valida', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('resumen_ia', sa.Column('recomendaciones_taller', sa.Text(), nullable=True))
    op.add_column('resumen_ia', sa.Column('motivo_rechazo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumen_ia', 'motivo_rechazo')
    op.drop_column('resumen_ia', 'recomendaciones_taller')
    op.drop_column('emergencia', 'es_valida')
    # ### end Alembic commands ###
