"""fix_fcm_token_fk

Revision ID: de6f3f90d0bf
Revises: 406d0bdf8bf2
Create Date: 2026-04-24 17:25:47.266498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6f3f90d0bf'
down_revision: Union[str, None] = '406d0bdf8bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcm_token', sa.Column('idCliente', sa.Integer(), nullable=True))
    op.alter_column('fcm_token', 'idUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_fcm_token_idCliente'), 'fcm_token', ['idCliente'], unique=False)
    op.create_foreign_key(None, 'fcm_token', 'cliente', ['idCliente'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fcm_token', type_='foreignkey')
    op.drop_index(op.f('ix_fcm_token_idCliente'), table_name='fcm_token')
    op.alter_column('fcm_token', 'idUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('fcm_token', 'idCliente')
    # ### end Alembic commands ###
